apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp
  template:
    metadata:
      labels:
        app: whatsapp
    spec:
      containers:
      - name: whatsapp-container
        # Pointing exactly to the repository and tag from your screenshot
        image: docker.io/ikonoim/whatsapp:v26.05.2rc1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: whatsapp
  ports:
    - port: 80
      targetPort: 80